export const GET_ORDERS_DATA_START = 'GET_ORDERS_DATA_START';
export const GET_ORDERS_DATA_SUCCESS = 'GET_ORDERS_DATA_SUCCESS';
export const GET_ORDERS_DATA_FAILURE = 'GET_ORDERS_DATA_FAILURE';
export const GET_ORDERS_DATA_RESET = 'GET_ORDERS_DATA_RESET';

export const SET_ORDER_ROUTE_START = 'SET_ORDER_ROUTE_START';
export const SET_ORDER_ROUTE_SUCCESS = 'SET_ORDER_ROUTE_SUCCESS';
export const SET_ORDER_ROUTE_FAILURE = 'SET_ORDER_ROUTE_FAILURE';
export const SET_ORDER_ROUTE_RESET = 'SET_ORDER_ROUTE_RESET';

export const GET_ORDERS_DATA_KEY = 'getOrderData';
export const SET_ORDER_ROUTE_KEY = 'setOrderRouter';
export const INITIAL_STATE_KEYS = [GET_ORDERS_DATA_KEY, SET_ORDER_ROUTE_KEY]
