export const GET_ORDERS_DATA_START = 'GET_ORDERS_DATA_START';
export const GET_ORDERS_DATA_SUCCESS = 'GET_ORDERS_DATA_SUCCESS';
export const GET_ORDERS_DATA_FAILURE = 'GET_ORDERS_DATA_FAILURE';
export const GET_ORDERS_DATA_RESET = 'GET_ORDERS_DATA_RESET';

export const GET_ORDERS_DATA_KEY = 'getOrderData';
export const INITIAL_STATE_KEYS = [GET_ORDERS_DATA_KEY]
